### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Katbruh** [AntiCope/orion#20]
### Describe the bug

Crash when open the game
[crash-2022-03-29_11.45.56-client.txt](https://github.com/AntiCope/orion/files/8368117/crash-2022-03-29_11.45.56-client.txt)
seems like RPC caused it

### Steps to reproduce

```plaintext
1.drop the orion file to mods
2.open the game
3.crash
...
```

### Operating System

Windows

### Orion Version

Last 1.18.1

### Meteor Version

1.18.1

### Minecraft Version

1.18.1

### Other mods

```plaintext
fabric-api-0.46.1+1.18
meteor-client-0.4.7-1401
```

**Comment by C10udburst** [comment]
It's because "last 1.18.1" version works on the last devbuild of meteor for 1.18.1, which is now unavaliable

You should use [the 1.18.2 version](https://github.com/AntiCope/orion/releases/tag/latest-1.18) with the latest devbuild for [1.18.2 instead](https://meteorclient.com/download?devBuild=latest)
